name: Update DNS
on:
  push:
    branches:
      - main
    paths:
      - "dns/zones/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update DNS on push to main
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.39.4"
      - run: cd dns && deno run -A src/main.ts
